name: Setup
description: Sets up the environment, loads turbo cache and installs dependencies
inputs:
  node-version:
    description: "Node version to use"
    required: true
    default: 22.x
runs:
  using: "composite"
  steps:
  - name: Cache turbo test
    uses: actions/cache@v4
    with:
      path: .turbo
      key: ${{ runner.os }}-turbo-${{ github.sha }}
      restore-keys: |
        ${{ runner.os }}-turbo-

  - name: Use Node.js ${{ inputs.node-version }}
    uses: actions/setup-node@v4
    with:
      node-version: ${{ inputs.node-version }}
      cache: yarn

  - name: Install dependencies
    shell: bash 
    run: yarn install --immutable
